trigger:
- main
- master
- staging/*

pr:
- main
- master

variables:
- group: adicup_releases_group_variables
- name: isMaster
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

jobs:
- job: Projects
  pool:
    name: Default
    demands:
      - agent.name -equals no-OS
  steps:
  - checkout: self
    fetchDepth: 50
    submodules: recursive
    clean: true
    persistCredentials: true
  - script: 'python ./build_projects.py $(Build.Repository.LocalPath) $(RELEASE_DIR)'
    displayName: 'Run projects build'
  - task: PublishPipelineArtifact@1
    condition: eq(variables.isMaster, true)
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/$(RELEASE_DIR)'
      artifact: '$(ARTIFACT_NAME)'
      publishLocation: 'pipeline'
